// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Js_exn = require("bs-platform/lib/js/js_exn.js");

function id(x) {
  return x;
}

function $$const(a, _) {
  return a;
}

function kite(_, b) {
  return b;
}

function non(f, x) {
  return !Curry._1(f, x);
}

function compose(f, g, x) {
  return Curry._1(f, Curry._1(g, x));
}

function compose3(f, g, h, x) {
  return Curry._1(f, Curry._1(g, Curry._1(h, x)));
}

function pipe(f, g, x) {
  return Curry._1(g, Curry._1(f, x));
}

function flip(f, x, y) {
  return Curry._2(f, y, x);
}

function apply(f, x) {
  return Curry._1(f, x);
}

function trush(a, b) {
  return Curry._1(b, a);
}

function forever(f) {
  try {
    Curry._1(f, /* () */0);
    Curry._1(f, /* () */0);
    Curry._1(f, /* () */0);
    var _param = /* () */0;
    while(true) {
      Curry._1(f, /* () */0);
      Curry._1(f, /* () */0);
      Curry._1(f, /* () */0);
      Curry._1(f, /* () */0);
      _param = /* () */0;
      continue ;
    };
  }
  catch (raw_e){
    return Js_exn.internalToOCamlException(raw_e);
  }
}

function on(f, g, x, y) {
  return Curry._2(f, Curry._1(g, x), Curry._1(g, y));
}

function ap(f, g, x) {
  return Curry._2(f, x, Curry._1(g, x));
}

function liftA2(f, g, h, x) {
  return Curry._2(f, Curry._1(g, x), Curry._1(h, x));
}

function jay(f, x, y, z) {
  return Curry._2(f, x, Curry._2(f, z, y));
}

function blackbird(f, g, x, y) {
  return Curry._1(f, Curry._2(g, x, y));
}

function fix(f) {
  var x = function (param, y) {
    var x$1 = param[1];
    return Curry._2(f, Curry._1(x$1, /* `X */[
                    88,
                    x$1
                  ]), y);
  };
  var partial_arg = /* `X */[
    88,
    x
  ];
  return Curry._1(f, (function (param) {
                return x(partial_arg, param);
              }));
}

var konst = $$const;

exports.id = id;
exports.$$const = $$const;
exports.konst = konst;
exports.kite = kite;
exports.non = non;
exports.compose = compose;
exports.compose3 = compose3;
exports.pipe = pipe;
exports.flip = flip;
exports.apply = apply;
exports.trush = trush;
exports.forever = forever;
exports.on = on;
exports.ap = ap;
exports.liftA2 = liftA2;
exports.jay = jay;
exports.blackbird = blackbird;
exports.fix = fix;
/* No side effect */
